vfinance/blueprints/admin.py
import os

from flask import render_template, flash, redirect, url_for, request, current_app, Blueprint, send_from_directory
from flask_login import login_required, current_user
from flask_ckeditor import upload_success, upload_fail
from vfinance.utils import lookup, redirect_back
from vfinance.forms import QuoteForm, TradeForm
from vfinance.models import User, TradeHistory, Portfolio, Watchlist
from vfinance.extensions import db
from vfinance.kchart import chart_plot_upload


admin_bp = Blueprint('admin', __name__)

@admin_bp.route('/quote', methods=["GET", "POST"])
@login_required
def get_quote():
    form = QuoteForm()
    if form.validate_on_submit():
        symbol = form.symbol.data
        
        quote = lookup(symbol)
        
        if quote:
            
            return redirect(url_for(".show_quote", symbol = symbol))
        else:
            flash("Cannot find", 'warning')
            return redirect_back()
    return render_template("admin/quote.html", form = form)
    

@admin_bp.route('/quote/<string:symbol>', methods =["GET","POST"])
@login_required
def show_quote(symbol):
    form = QuoteForm()
    quote = lookup(symbol)
    company = quote["name"]
    price = quote["price"]
    symbol = quote['symbol']
    
    # link = chart_plot_upload(symbol)
    # if form.validate_on_submit():
    #     symbol = form.symbol.data
    #     quote = lookup(symbol)
    #     company = quote["name"]
    #     price = quote["price"]
    #     return redirect(url_for(".show_quote", symbol = symbol))
    return render_template("admin/show_quote.html",form = form, company = company, price = price, symbol = symbol)


@admin_bp.route("/trade/<string:symbol>", methods=['GET', 'POST'])
@login_required
def get_trade(symbol):
    # symbol = request.args.get("symbol")
    form = TradeForm()
    quote = lookup(symbol)
    if form.validate_on_submit():
        symbol = form.symbol.data
        quantity = form.quantity.data
        price = form.price.data
        action = form.action.data
        return redirect(url_for('.review_order', symbol = symbol, quantity= quantity, price = price, action = action))
    form.symbol.data = symbol
    form.price.data = quote['price']
    return render_template("admin/get_trade.html", form = form)

# @admin_bp.route('/trade/review/<string:symbol>/<int:quantity>/<float:price>', methods=['GET', 'POST'])
# @login_required
# def review_order(symbol, quantity, price):
    
#     return render_template("admin/review_order.html", symbol = symbol, price = price, quantity = quantity)

@admin_bp.route('/trade/review', methods=['GET', 'POST'])
@login_required
def review_order():
    cash = current_user.cash
    symbol = request.args.get('symbol')
    price = request.args.get('price')
    quantity = request.args.get('quantity')
    action = request.args.get('action')
    totalprice = float(price)*float(quantity)
    able_to_trade = True
    stocklist = []
    if action == 'Buy':
        cash_balance = float(cash) - totalprice
        if cash_balance < 0:
            able_to_trade = False
            flash("Your order be rejected if you do not have enough cash to cover this closing transaction.", 'danger')
            return redirect_back()
    else:
        cash_balance = float(cash) + totalprice
        portfolio = Portfolio.query.with_parent(current_user).all()
        # check if any existed portfolio, if no, return direct_back
        if portfolio:
        
            for company in portfolio:    
                stocklist.append(company.symbol)
            
            if symbol in stocklist:
                id = company.id
                stock = Portfolio.query.get_or_404(id)
                own_quantity = float(stock.quantity)
                if float(quantity) > own_quantity:
                    able_to_trade = False
                    flash("Your share isn't enough for the trade. the order was rejected", 'danger')
                    return redirect_back()
            else:
                flash("You dont have any share yet", 'danger')
                return redirect_back()

            #     if symbol in company.symbol:
            #         id = company.id
            #         stock = Portfolio.query.get_or_404(id) 
            #         own_quantity = float(stock.quantity)
            #         if float(quantity) > own_quantity:
            #             able_to_trade = False
            #             flash("Your share isn't enough for the trade. the order was rejected", 'danger')
            #             return redirect_back()
            
            # flash("You dont have any share yet", 'danger')
            # return redirect_back()      
        else:
           able_to_trade = False
           flash("You portfolio is empty", 'danger')
           return redirect_back()
        
    # if cash_balance < 0:
    #     flash("You dont have enough money", 'danger')
    #     return redirect_back()
     
    return render_template("admin/review_order.html",able_to_trade = able_to_trade, action = action, symbol = symbol, price= price, quantity = quantity, cash = cash, totalprice=totalprice, cash_balance=cash_balance)

@admin_bp.route('/trade/placeorder', methods=['GET', 'POST'])
@login_required
def place_order():
    # get trade condition
    able_to_trade = request.args.get('able_to_trade')
    action = request.args.get("action")
    if able_to_trade:
        # get original cash and position
        cash = float(current_user.cash)
        # position = float(current_user.position)
        

        # update cash and position back to database
        if action =="Buy":
            totalprice = float(request.args.get('totalprice'))
            current_user.cash = cash - totalprice
            # current_user.position = position + totalprice
        else:
            totalprice = float(request.args.get('totalprice'))
            current_user.cash = cash + totalprice
            # current_user.position = position - totalprice

        #update trade_history
        symbol = request.args.get('symbol')
        name = lookup(symbol)['name']
        price = request.args.get('price')
        quantity = request.args.get('quantity')
        
        
        
        trade_history = TradeHistory(symbol = symbol, name = name, price = price, action = action, quantity = quantity)
        db.session.add(trade_history)
        current_user.trade_history.append(trade_history)

        # update portfolio
        portfolio = Portfolio.query.with_parent(current_user).all()
        if portfolio:
            # check if the stock already existed
            for company in portfolio:
            # if exists update the averge pruchase price and quantity
                if symbol == company.symbol:
                    # get purchase price and symbol
                    id = company.id
                    stock = Portfolio.query.get_or_404(id)
                    purchase_price = float(stock.purchase_price)
                    own_quantity = float(stock.quantity)

                    # caculate new purchase price and quantity
                    if action =="Buy":
                        new_purchase_price = (purchase_price * own_quantity + float(quantity) * float(price))/(own_quantity + float(quantity))
                        new_own_quantity = own_quantity + float(quantity)
                    else:
                        new_own_quantity = own_quantity - float(quantity)
                        if new_own_quantity == 0:
                            db.session.delete(stock)
                            db.session.commit()
                            return redirect(url_for('home.index'))
        
                        new_purchase_price = (purchase_price*own_quantity - float(quantity) * float(price))/(own_quantity-float(quantity))
                        

                    stock.purchase_price = new_purchase_price
                    stock.quantity =new_own_quantity
                    db.session.commit()
                    return redirect(url_for("home.index"))
            # if not exist in portfolio, create it    
            new_portfolio = Portfolio(symbol = symbol, name = name, purchase_price = price, quantity = quantity)
            current_user.portfolio.append(new_portfolio)
        else:
            new_portfolio = Portfolio(symbol = symbol, name = name, purchase_price = price, quantity = quantity)
            current_user.portfolio.append(new_portfolio)

    db.session.commit()
    return redirect(url_for("home.index"))

@admin_bp.route("/trade_history", methods=['GET', 'POST'])
@login_required
def trade_history():
    # get data from database
    page = request.args.get('page', 1, type=int)
    per_page = 10
    pagination = TradeHistory.query.with_parent(current_user).order_by(TradeHistory.timestamp.desc()).paginate(page, per_page)
    trade_history = pagination.items
    return render_template("admin/trade_history.html", trade_history = trade_history, pagination = pagination)





@admin_bp.route('/watchlist')
@login_required
def show_watchlist():
    form = QuoteForm()
    page = request.args.get('page',1, type= int)
    per_page = 10
    pagination = Watchlist.query.with_parent(current_user).order_by(Watchlist.symbol.asc()).paginate(page, per_page)
    watchlist = pagination.items

    symbols=[] 
    prices =[]         
    changes =[]
    changePercents =[]
    openprices =[]
    highs =[]
    lows =[]
    volumes =[]
    week52Highs =[]
    week52Lows  =[]

    if watchlist:
        for stock in watchlist:
            quote = lookup(stock.symbol)
            
            price= quote["price"]
            symbol= quote["symbol"]
            change= quote["change"]
            changePercent= quote["changePercent"]
            volume= quote["volume"]
            week52High= quote["week52High"]
            week52Low= quote["week52Low"]
            openprice =quote["open"]
            high =quote['high']
            low = quote["low"]

            symbols.append(symbol)

vfinance/blueprints/auth.py
import os
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_user, logout_user, login_required, current_user

from vfinance.extensions import db
from vfinance.forms import LoginForm, RegisterForm
from vfinance.models import User
from vfinance.utils import redirect_back
from sqlalchemy.exc import IntegrityError



auth_bp = Blueprint('auth', __name__)

@auth_bp.route("/register", methods = ["GET", "POST"])
def register():
    form = RegisterForm()
    
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        cash = 1000000
        user = User(
            username = username,
            cash = cash,
            position = 0
        )
        user.set_password(password)
        db.session.add(user)
        try:
            db.session.commit()
            flash("Thanks for registering! Please login!", 'success' )
            
        except IntegrityError:
            flash("Account already exists", 'danger')
            db.session.rollback()
            return redirect_back()
        return redirect(url_for('home.index'))
        

    return render_template("auth/register.html", form = form)



@auth_bp.route("/login", methods = ["GET", "POST"])
def login():
    form = LoginForm()
    if current_user.is_authenticated:
        # flash('You are already loging','success')
        return redirect(url_for("home.index"))
    
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        remember = form.remember.data
        users = User.query.all()
        
        for user in users:
            if username in user.username:
                if user.validate_password(password):
                    login_user(user,remember)
                    flash('Welcome Back '+user.username, 'info')
                    return redirect_back()
                # flash("Invalid username or password.", 'warning')
                else:
                    flash("Invalid username or password.", 'warning')
            
                
       
    return render_template("auth/login.html", form = form)

@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logout success.', 'info')
    return redirect_back()

vfinance/templates/base.html
{% from 'bootstrap/nav.html' import render_nav_item %}
<!DOCTYPE html>

<html lang="en">

<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- documentation at http://getbootstrap.com/docs/4.1/, alternative themes at https://bootswatch.com/ -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet">

    <!-- https://favicon.io/emoji-favicons/money-mouth-face/ -->
    <link rel="icon" href="{{ url_for('static', filename = 'favicon.ico') }}">

    <!-- css sheet -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}" type ='text/css'>

    <title>C$50 Finance: {% block title %}{% endblock %}</title>

</head>

<body>
{% block nav %}
    <nav class="navbar navbar-expand-md navbar-light bg-light border">
        <div class="container">

        

            <!-- navbar brand -->
            <a class="navbar-brand" href="/"><span class="blue">C</span><span class="red">$</span><span class="yellow">5</span><span class="green">0</span> <span class="red">Finance</span></a>
            
            <!-- Hambuger Button -->
            <button aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbar" data-toggle="collapse" type="button">
                <span class="navbar-toggler-icon"></span>
            </button>

            {% if current_user.is_authenticated %}
            <div class="collapse navbar-collapse">
                <ul class= 'nav navbar-nav mr-auto'>
                    
                    <!-- <li class = 'nav-item dropdown'>
                        <a href="#" class='nav-link dropdown-toggle' data-toggle='dropdown' role = 'button' aria-haspopup='true' area-expanded='false'>
                        Quote <span class='caret'></span>
                        </a>
                        <div class='dropdown-menu' aria-labelledby='navbarDropdown'>
                            <a class='dropdown-item' href = "{{ url_for('admin.get_quote') }}">Get Quote</a>
                            <a class='dropdown-item' href = "#">History</a>                
                        </div>
                        
                    </li> -->
                    <li class = 'nav-item dropdown'>
                        <a href="#" class='nav-link dropdown-toggle' data-toggle='dropdown' role = 'button' aria-haspopup='true' area-expanded='false'>
                        My Account <span class='caret'></span>
                        </a>
                        <div class='dropdown-menu' aria-labelledby='navbarDropdown'>
                            <a class='dropdown-item' href = "/">Portifolio</a>
                            <a class='dropdown-item' href = "{{ url_for('admin.trade_history')}}">History</a>
                            <a class='dropdown-item' href = "{{ url_for('admin.show_watchlist')}}">Watchlist</a>     
                        </div>
                    </li>
                    <li class = 'nav-item dropdown'>
                        <a href="#" class='nav-link dropdown-toggle' data-toggle='dropdown' role = 'button' aria-haspopup='true' area-expanded='false'>
                        Trade <span class='caret'></span>
                        </a>
                        <div class='dropdown-menu' aria-labelledby='navbarDropdown'>
                            <a class='dropdown-item' href = "{{ url_for('admin.get_quote')}}">Buy</a>
                            <a class='dropdown-item' href = "#">Sell</a>
                            
                        </div>
                    </li>
                    <li class = 'nav-item dropdown'>
                        <a href="#" class='nav-link dropdown-toggle' data-toggle='dropdown' role = 'button' aria-haspopup='true' area-expanded='false'>
                        BackTest <span class='caret'></span>
                        </a>
                    </li>
                    
                    
                </ul>

            </div>
            <div class="navbar-collapse collapse ">
                
                <ul class="navbar-nav ml-auto">
                    <form class="form-inline my-2 my-lg-0" method = 'post'
                        action="{{ url_for('admin.get_quote') }}">
                        {% if form %}
                        {{form.csrf_token}}    
                        {% endif %}
                        

                    <input class="form-control mr-sm-2" type="search" placeholder="Search"  aria-label="Search" id ='symbol' name = 'symbol'>
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Quote</button>
                    </form>
                    <li class="nav-item">
                        <a class="nav-link" href="#">{{ current_user.username }}</a>
                    </li> 
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout', next = request.full_path) }}">logout</a>
                    </li>             
                </ul>
            </div>
            {% else %}
            <div class="collapse navbar-collapse">           
                <ul class="nav navbar-nav navbar-right">
                    {{ render_nav_item('auth.register', "Register") }}
                    {{ render_nav_item('auth.login', "Login") }}
                </ul>
            </div>
            {% endif %}


        </div>
    </nav>
{% endblock nav %}    
<main class="container p-5">
    {% for message in get_flashed_messages(with_categories=True) %}
    <div class="alert alert-{{ message[0]}}" role='alert'>
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message[1]}}
    </div>

    {% endfor %}

    
        {% block content %}{% endblock %}
    
    <footer class="small text-center text-muted">
        Data provided for free by <a href="https://iextrading.com/developer">IEX</a>. View <a href="https://iextrading.com/api-exhibit-a/">IEX’s Terms of Use</a>.
    </footer>

</main>

{% block scripts %} 
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.2.1.slim.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/script.js') }}"></script>
{{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
{% endblock scripts %}  




</body>
</html>